### PR TITLE
Disable using default styles

### LINKED ISSUE #24: Is there an easy way to drop the default styles?
making it configurable would be just fine. Thanks.

### PR DESCRIPTION
**Pull request by Janekk**
Add new prop Tabs.useDefaultStyles (be default set to true). Resolves #24

### CODE REVIEW

**Comment by liady** [comment]
:+1:

**Comment by mzabriskie** [comment]
In cases where you want to disabled styles, wouldn't you want it across the entire app? I'm just thinking that it would be repetitive to have to use the `useDefaultStyles` prop on each `<Tabs/>` component. An alternate would be to use a static method directly on the class `Tabs.setUseDefaultStyles(false);`.

**Comment by Janekk** [comment]
yea @mzabriskie I noticed that later on that with the proposed solution resetting would have been repetitive. Doing it globally with a static method makes more sense.

**Comment by Janekk** [comment]
Ok, updated the PR. Now there's a static method on `Tabs` component `useDefaultStyles` to turn on / off default styling globally @mzabriskie

**Comment by danez** [comment]
:+1:

**Comment by jkarttunen** [comment]
Add this to documentation, maybe?

**Comment by jkarttunen** [comment]
@Janekk Maybe update readme too.

**Comment by jkarttunen** [comment]
It would be useful to support className prop.
Re-styling using CSS systems that avoid complicated selectors (like BEM) is difficult if the classNames cannot be added. 

      <Tabs className="my_navi" selectedIndex={0}>
       <TabList >
        <Tab className="my_navi_tab">Foo</Tab>
       </TabList>
       <TabPanel className="my_navi__tab_panel_foo">
         <h2>Hello from Foo</h2>
       </TabPanel>
      </Tabs>

**Comment by sgronblo** [comment]
I would also like to request the same support for className as @jkarttunen Should we open a new issue for it?

**Comment by Janekk** [comment]
@jkarttunen ok I will update readme
@sgronblo yes I suppose a new issue would be better.

**Comment by tedtoer** [comment]
nice one!!! want it

**Comment by vojtatranta** [comment]
MERGE IT!! @mzabriskie

**Comment by sgronblo** [comment]
Is this project maintained any more?

**Comment by amannn** [comment]
Oh it would be great to disable the styles. Also custom classNames would be just what I need.

**Comment by zebapy** [comment]
So how do you even disable the styles?

**Comment by micky2be** [comment]
Also not sure why using <ul> and <li> tags? It's a pain to restyle it.
We are not in the 90s anymore just use plain divs.

**Pull request merged**
